<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * The full list of valid order statuses (11 stages including picked_up & delivered).
     *
     * @var string[]
     */
    private array $statuses = [
        'pending',
        'out_for_pickup',
        'picked_up',
        'received',
        'washing',
        'rinsing',
        'drying',
        'finish',
        'out_for_delivery',
        'delivered',
        'completed',
        'cancelled',
    ];

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $driver = DB::getDriverName();

        if ($driver === 'pgsql') {
            $list = implode("', '", $this->statuses);

            // --- orders table ---
            // Drop the old check constraint (name is auto-generated by Laravel/Postgres)
            DB::statement('ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_order_status_check');
            // Add new constraint with full status list
            DB::statement("ALTER TABLE orders ADD CONSTRAINT orders_order_status_check CHECK (order_status IN ('{$list}'))");

            // --- order_status_history table ---
            DB::statement('ALTER TABLE order_status_history DROP CONSTRAINT IF EXISTS order_status_history_status_check');
            DB::statement("ALTER TABLE order_status_history ADD CONSTRAINT order_status_history_status_check CHECK (status IN ('{$list}'))");

        } elseif ($driver === 'mysql') {
            $list = implode("', '", $this->statuses);

            try {
                DB::statement("ALTER TABLE orders MODIFY COLUMN order_status ENUM('{$list}') NOT NULL DEFAULT 'pending'");
            } catch (Throwable $e) {
                // Already varchar or enum update not needed
            }

            try {
                DB::statement("ALTER TABLE order_status_history MODIFY COLUMN status ENUM('{$list}') NOT NULL DEFAULT 'pending'");
            } catch (Throwable $e) {
                // Already varchar or enum update not needed
            }
        }
        // SQLite has no check constraints to update — no action needed
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $driver = DB::getDriverName();

        if ($driver === 'pgsql') {
            // Restore the old constraint (without picked_up and delivered)
            $oldStatuses = [
                'pending', 'out_for_pickup', 'received', 'washing', 'rinsing',
                'drying', 'finish', 'out_for_delivery', 'completed', 'cancelled',
            ];
            $list = implode("', '", $oldStatuses);

            DB::statement('ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_order_status_check');
            DB::statement("ALTER TABLE orders ADD CONSTRAINT orders_order_status_check CHECK (order_status IN ('{$list}'))");

            DB::statement('ALTER TABLE order_status_history DROP CONSTRAINT IF EXISTS order_status_history_status_check');
            DB::statement("ALTER TABLE order_status_history ADD CONSTRAINT order_status_history_status_check CHECK (status IN ('{$list}'))");
        }
    }
};
